import os
import json
from datetime import datetime, timezone, timedelta
from .context_builder import (
    load_zone_configs,
    resolve_location_from_zone,
    get_weather_context,
)
import psycopg2
from psycopg2.extras import Json

from shared import load_environment, build_dsn_from_env
from .status_logger import update_status

load_environment()

DB_DSN_CONTROLCORE = build_dsn_from_env("controlcore", "CONTROLCORE_USER", "CONTROLCORE_PW")


from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


def load_json_config(path: str | Path):
    config_path = BASE_DIR / path
    with open(config_path) as f:
        return json.load(f)

plant_profiles = load_json_config("configs/plant_profiles.json")
method_config = load_json_config("configs/application_methods.json")



watering_windows = {
    "early_morning": (4, 8),
    "morning_or_evening": [(6, 10), (18, 21)],
    "evening_only": (17, 21),
    "early_morning_or_night": [(4, 8), (20, 23)],
}



def advise_watering(zone, weather):
    reasons = []
    decision = "water"  # default

    hourly_pops = weather.get("hourly_pop_windows", {})
    recent_rain = weather.get("recent_rain_mm_last_3_days", 0)

    # Count high-confidence rain hours
    heavy_hours = [pop for pop in hourly_pops.values() if pop >= 0.9]
    trust_forecast = len(heavy_hours) >= 4

    if recent_rain >= 10:
        decision = "skip"
        reasons.append(f"🌧️ Got {recent_rain:.1f}mm of rain in the last 3 days")
    elif trust_forecast:
        decision = "skip"
        reasons.append("🌦️ High-confidence forecast: sustained heavy rain expected")
    else:
        if recent_rain > 0:
            reasons.append(f"💧 Only {recent_rain:.1f}mm rain in last 3 days — not enough")
        if heavy_hours:
            reasons.append(f"⛅ Only {len(heavy_hours)} high-PoP hours — insufficient to skip")

    return decision, reasons

def insert_or_update_watering_schedule(zone, start_time, duration_sec, reasoning, weather_context):
    metadata = {
        "advisor_reasoning": reasoning,
        "forecast_snapshot_time": (
            weather_context["forecast_time"].isoformat()
            if isinstance(weather_context.get("forecast_time"), datetime)
            else weather_context.get("forecast_time")
        ),
        "advisor_run_time": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "temperature_max_forecast": weather_context.get("today_temp_max_forecast"),
        "preferred_watering_window": zone.get("preferred_watering_window", "early_morning"),
        "plant_profiles": zone.get("plants", []),
        "application_method": zone.get("application_method"),
    }

    source_id = f"{zone['location']}_{zone['station']}_{zone['controller']}_valve-state_{zone['sensor_id']}"

    try:
        with psycopg2.connect(DB_DSN_CONTROLCORE) as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    INSERT INTO watering_schedule (
                        zone_id, sensor_id, source_id, station, controller_id,
                        start_time, duration_seconds, requestor_id, metadata, notes
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (zone_id, start_time) DO UPDATE
                    SET duration_seconds = EXCLUDED.duration_seconds,
                        metadata = EXCLUDED.metadata,
                        status = 'scheduled',
                        confirmed_execution = FALSE,
                        last_updated = now(),
                        notes = EXCLUDED.notes
                """, (
                    zone["zone_id"],
                    zone["sensor_id"],
                    source_id,
                    zone["station"],
                    zone["controller"],
                    start_time,
                    duration_sec,
                    "advisor",
                    Json(metadata),
                    "Auto-generated by advisor"
                ))
    except Exception as e:
        print(f"[advisor] Failed to insert schedule for {zone['zone_id']}: {e}")


def pick_best_start_time(now_utc, zone, plant_profiles, method_config):
    # Collect preferred time windows from plants
    windows = []
    for plant_name in zone["plants"]:
        plant = plant_profiles.get(plant_name)
        if plant:
            pref = plant.get("water_pref_time")
            if pref and pref in watering_windows:
                windows.extend(watering_windows[pref])

    # Also consider method timing advice
    method = method_config.get(zone["application_method"], {})
    method_timing = method.get("timing_advice")
    if method_timing in watering_windows:
        windows.extend(watering_windows[method_timing])

    # Normalize to a flat list of (start_hour, end_hour) tuples
    slot_list = []
    for win in windows:
        if isinstance(win, tuple):
            slot_list.append(win)
        elif isinstance(win, list):
            slot_list.extend(win)

    # Sort and pick the next upcoming viable time slot
    for start_hr, end_hr in sorted(slot_list):
        candidate = now_utc.replace(hour=start_hr, minute=0, second=0, microsecond=0)
        if candidate < now_utc:
            candidate += timedelta(days=1)
        return candidate  # Use first viable slot

    # Fallback: default to tomorrow at 5AM
    fallback = now_utc.replace(hour=5, minute=0, second=0, microsecond=0)
    if now_utc.hour >= 5:
        fallback += timedelta(days=1)
    return fallback



if __name__ == "__main__":
    zones = load_zone_configs()
    now = datetime.now(timezone.utc)

    for zone in zones:
        location_id = resolve_location_from_zone(zone)
        if not location_id:
            continue

        print(f"\n=== Advice for Zone: {zone['zone_id']} ===")
        weather = get_weather_context(location_id, now)
        decision, reasons = advise_watering(zone, weather)

        if decision == "water":
            # Use zone["duration_default_minutes"] or later duration calculator
            duration_sec = zone.get("duration_default_minutes", 60) * 60

            # Choose next start time based on time of day or advisor logic
            planned_start = pick_best_start_time(now, zone, plant_profiles, method_config)

            insert_or_update_watering_schedule(zone, planned_start, duration_sec, reasons, weather)

        print(f"\U0001F4CD Advice: {decision}")
        for reason in reasons:
            print(f"  - {reason}")

    update_status("advisor", "completed", {"zones": len(zones)})
